### PR TITLE
Create test workflow

### LINKED ISSUE #6: Add testing using Github Actions
Tests are currently run using `python setup.py test`

### PR DESCRIPTION
**Pull request by techgerm**
Resolves #6

### CODE REVIEW

**Review by maroux — COMMENTED** [review]
Missing install dependencies step.

**Comment by techgerm** [comment]
hmmm I was actually testing it locally and playing with migrating over to `pytest` since it looks like it's still having issues after installing dependencies. This side of python I'm not too familiar with so I'm sort of experimenting here.

**Comment by techgerm** [comment]
alright that should be good for now ... let me know what you think.

**Review by maroux — APPROVED** [review]
I'd just update setup.py to include wheel dependency and remove it from actions - but this can be done later.

**Comment by techgerm** [comment]
quick update ... I can do that right now 👍

**Comment by maroux** [comment]
I just updated the repo so these checks are now required to merge! ❇️

**Comment by techgerm** [comment]
shit ... bare with me ... still getting up to speed with `setup.py` stuff.

**Comment by techgerm** [comment]
erg I guess `wheel` needs to be specified in `install_requires` and not `tests_require`?

**Pull request merged**
