### PR TITLE
Add DATE field type and support for multiple array types

### PR DESCRIPTION
**Pull request by techgerm**

### CODE REVIEW

**Review by maroux — APPROVED** [review]

**Comment by maroux** [comment]
thanks for the contribution @germanp173

**Comment by techgerm** [comment]
@maroux thanks for the quick response!

**Comment by techgerm** [comment]
@maroux do you usually publish a new version to PyPi on every master merge or what is your cadence?

**Comment by maroux** [comment]
So far it has been ad-hoc - will probably move to weekly at some point.

Btw, if you are planning more work on this repo, 2 things you should know - this was originally forked from google/python-spanner-orm which is not taking any contributations (at least not actively), but I set this up as a new repo only because I plan to break compatibility with google's repo by re-indenting all the code here. Hate the 2-space indent that exists right now. Second - once the 2-space indent lands your in-progress PRs (if any) will require painful merging. However, I don't have any particular timeline in mind for this work, so if you have planned work, I can postpone the re-indent.

I did have a few more changes in mind which I'll add to the README.

**Comment by techgerm** [comment]
Yup, I originally intended to use the `google/python-spanner-orm` for a serious business project but was let down to see it's not actively maintained. I saw that you had created some solid PRs on their repo which is how I found your forked version.

On your 2-space indent point, totally on board with that! In our company, we use `black` as our formatter and I usually have `vscode` automatically format all the code using `black`. I actually had to disable it on this project to submit my recent PRs.

Also, are you open to setting up a GitHub action that automatically publishes a new version to PyPi (and tags repo) on master merges? I can help out with that if so.

**Comment by maroux** [comment]
@germanp173 yeah Github action for both 1. running tests and 2. publishing new version sounds good. 

Tests are `python setup.py test` right now but should be changed to pytest in the future.
Publishing new version - since the version is part of code for python libs, it could be set up one of two ways -

1. Trigger on new tag. Script would update setup.py file locally, then publish to pypi and finally create tag in the repo (but not push the commit). Under this workflow, releasing a new version would simply require pushing a new tag, however the version in setup.py would be out of date with reality - could simply change that file to not have a real version on master branch.
2. Trigger by a PR where `setup.py` version is changed to a value that doesn't match any existing tags. Script would publish to pypi and create tag in the repo. Under this workflow, releasing a new version would mean creating a new PR for change to setup.py and the file would have accurate version number.

I usually do workflow 2 (with bumpversion / bump2version) but that does mean git commits are cluttered with "update version" commits which is a little annoying. I've been meaning to try out workflow 1 so we can do that with this repo if that sounds good.

**Comment by techgerm** [comment]
@maroux Actions for running tests and publishing would be great 💯 

In your scenario 1, why not let GitHub actions push the commit so master is not out of date with reality? That's what we do in our company since we have the same situation where our npm packages hold the version in the `package.json`.

**Comment by maroux** [comment]
Well for repos that don't get a lot of commits, it tends to clutter git history by adding one additional version bump commit for every code commit but that's how most python repos look so not a big deal.

Thinking some more - the trigger should probably be a PR submitted by a maintainer with some command-tag like `/make-release`? Github Actions can then take all the appropriate actions and close the PR.

**Comment by techgerm** [comment]
I see and yeah that sounds better 👌

Side question, do you think I can get an estimate release date for the next release? Asking since we could really use those changes I made.

**Comment by maroux** [comment]
Done.

**Comment by techgerm** [comment]
Awesome thank you very much!

**Pull request merged**
