### PR TITLE
Add fake flag to migrations and add helpful print statements

### LINKED ISSUE #16: Add Command to Seed Migrations Table
**Consider the following scenario:**
* A developer wants to stand up a development/staging Spanner DB
* Developer creates DB with the latest models from a `master` branch
* In order to continue development, the developer would need to make sure that all migrations are marked as true in the new dev/staging database to ensure none of the current migrations in the repo are executed.

**Proposed solution:**
* `MigrationExecutor` should have a `seed_migrations_table` function that seeds the migrations table with all the current migrations in the repo.

### PR DESCRIPTION
**Pull request by techgerm**
* Issues:
    * https://github.com/maroux/python-spanner-orm/issues/16
    * https://github.com/maroux/python-spanner-orm/issues/4
* Tested this well on a live Spanner DB and works/looks good 👍

### CODE REVIEW

**Review by maroux — COMMENTED** [review]
also CLI flag for `--fake`?

**Comment by techgerm** [comment]
Yup, had forgotten about that ... on it

**Review by maroux — APPROVED** [review]

**Comment by techgerm** [comment]
Got a quick minute to merge this in? Just need to submit one more PR that might conflict with this branch.

**Comment by maroux** [comment]
> Got a quick minute to merge this in? Just need to submit one more PR that might conflict with this branch.

ah sorry thought I pressed the button

**Pull request merged**
