### PR TITLE
Frozen CreateTable operation so making changes to schema is actually possible

### PR DESCRIPTION
**Pull request by maroux**
Migrations should use schema definition frozen in time at the time of creation so that updating models code doesn't automatically affect a historical migration.

- Also check black formatting in tests

### CODE REVIEW

**Comment by techgerm** [comment]
Can you elaborate a little more on "frozen CreateTable" and "so making changes to schema is actually possible"? Do you mean as opposed to making migrations? I'm trying to follow your reasoning while reviewing your code.

**Comment by maroux** [comment]
> Can you elaborate a little more on "frozen CreateTable" and "so making changes to schema is actually possible"? Do you mean as opposed to making migrations? I'm trying to follow your reasoning while reviewing your code.

If you create a migration with operation `CreateTable(model)` and then remove a field, that migration will not create the field in a new database. Instead, it should create the model frozen in time, such that when its applied again - the field is created and then later dropped using a different migration. Without doing it this way, running migrations in test code isn't possible because the field you want to drop would not exist.

**Comment by maroux** [comment]
This is similar to how alembic migrations work - the list of fields, types, indexes etc are frozen when migration is created.

**Comment by techgerm** [comment]
Ah gotcha, makes sense ... thanks for elaborating 👌

**Review by techgerm — APPROVED** [review]

**Pull request merged**
